AllCops:
  Exclude:
    - "bundler/**/*"
    - "vendor/**/*"
    - "bin/**/*"

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Layout/IndentationWidth:
  Width: 4

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 30

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Enabled: false
