AllCops:
  Exclude:
    - 'bundler/'
    - "vendor/"

Style/IfUnlessModifier:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrivialAccessors:
  Enabled: false

Layout/IndentationWidth:
  Width: 4

Layout/MultilineOperationIndentation:
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 30

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Max: 100

Metrics/CyclomaticComplexity:
  Enabled: false
